# Generated by Django 4.2 on 2023-04-27 15:39

from django.db import migrations

def create_data(apps, schem_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Paul Wathome", email="pwathome@local.com", document="222342342", phone="555-555-5555").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
